### ISSUE TITLE
error from sender: resolve : lstat deploy: no such file or directory

### ISSUE THREAD

**Issue by Uranium2** [Azure/AzureML-Containers#162]
I'm using AML SDK v2 to create my Environment. But it is failing to create my iamge from my dockerfile.

```python
from azure.identity import DefaultAzureCredential
from azure.ai.ml import MLClient

from azure.ai.ml.entities import Environment, BuildContext

credential = DefaultAzureCredential()
ml_client = MLClient.from_config(
    credential=credential, path=f"config/aml_config.json"
    )


azureml_env = Environment(
    build=BuildContext(
        path="deploy/utils/docker_context",
        dockerfile_path="deploy/utils/docker_context/Dockerfile",
    ),
    name="my_ref_image",
)
azureml_env.validate()

ml_client.environments.create_or_update(azureml_env)
```

It creates me a job on AML but it fails to find or copy Dockerfile:

Here is the content of my `Dockerfile`:

```dockerfile
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest

RUN mkdir -p /usr/share/man/man1

RUN apt-get -y update \
    && apt-get install  openjdk-19-jdk -y \
    && rm -rf /var/lib/apt/lists/*

```
I did not find any azureml using java for Databricks/Spark usage, this is why I'm trying to build my own. If you have a default one, maybe it can help me even more.

![image](https://github.com/Azure/AzureML-Containers/assets/6902440/5d9c0a87-57a3-42b5-9cb8-37a6dbcbe248)

Also, I'd like to find a way to create the conda env with a environment.yml file:

```dockerfile
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest

RUN mkdir -p /usr/share/man/man1

RUN apt-get -y update \
    && apt-get install  openjdk-19-jdk -y \
    && rm -rf /var/lib/apt/lists/*

COPY ./environments.yaml ./environments.yaml

RUN conda create -n py38 python=3.8 --file ./environments.yaml && \
    echo ". /opt/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate py38" >> ~/.bashrc

# Make all RUN use conda
SHELL ["conda", "run", "-n", "py38", "/bin/bash", "-c"]

```

Here is the error log from AML Job:

```log
get ws context from the run
get environment to build
Environment(Name: my_ref_image,
Version: 2)
build and push
Saving setup content into  /tmp/tmp051kf0c9

Materialized image not found on target: azureml/azureml_433365a17423de62b0cf220fba3a526d
Running: ['docker', 'build', '-f', 'deploy/utils/docker_context/Dockerfile', '-t', 'azureml/azureml_433365a17423de62b0cf220fba3a526d', '.']
#2 [internal] load build definition from Dockerfile
#2 sha256:11d2810e092d207f7b87c5769677ddf51ee8413fafbe83b3ca99d8b189941266
#2 transferring dockerfile: 53B done
#2 ERROR: error from sender: resolve : lstat deploy: no such file or directory

#1 [internal] load .dockerignore
#1 sha256:80ea39bbea934791c63f8571d43a653545fbeed3f6b9642433d768fa41f1b02b
#1 transferring context: 2B done
#1 DONE 0.1s
------
 > [internal] load build definition from Dockerfile:
------
failed to read dockerfile: error from sender: resolve : lstat deploy: no such file or directory


CalledProcessError(1, ['docker', 'build', '-f', 'deploy/utils/docker_context/Dockerfile', '-t', 'azureml/azureml_433365a17423de62b0cf220fba3a526d', '.'])

Building docker image failed with exit code: 1

Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.09904646873474121 seconds
Traceback (most recent call last):
  File "/azureml-envs/image-build/lib/python3.7/site-packages/azureml/core/environment.py", line 1499, in _build_environment
    stderr=sys.stderr, cwd=setup_temp_dir, env=env)
  File "/azureml-envs/image-build/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-c', '/tmp/tmp051kf0c9/azureml-environment-setup/docker_env_checker.sh']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/azureml-envs/image-build/lib/python3.7/site-packages/azureml/core/environment.py", line 1343, in build_local
    self._build_environment(setup_temp_dir, check_script, build_script, environment_variables)
  File "/azureml-envs/image-build/lib/python3.7/site-packages/azureml/core/environment.py", line 1503, in _build_environment
    stderr=sys.stderr, cwd=setup_temp_dir, env=env)
  File "/azureml-envs/image-build/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-c', '/tmp/tmp051kf0c9/azureml-environment-setup/docker_env_builder.sh']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prepare.py", line 26, in <module>
    build_local_environment(args.name, args.version, args.platform)
  File "prepare.py", line 15, in build_local_environment
    environment.build_local(workspace, platform, useDocker=True, pushImageToWorkspaceAcr=True)
  File "/azureml-envs/image-build/lib/python3.7/site-packages/azureml/core/environment.py", line 1345, in build_local
    raise Exception("Building environment failed with exit code: {}".format(ex.returncode))
Exception: Building environment failed with exit code: 1
```

**Comment by Uranium2** [comment]
Found out that I should not specify the argument `dockerfile_path` ...


```python
azureml_env = Environment(
    build=BuildContext(
        path="deploy/utils/docker_context",
        dockerfile_path="deploy/utils/docker_context/Dockerfile",
    ),
    name="my_ref_image",
)
```
